name: RDP with ngrok

on:
  workflow_dispatch:

jobs:
  rdp-ngrok:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download ngrok
        run: |
          Invoke-WebRequest -Uri https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
          Expand-Archive ngrok.zip -DestinationPath ngrok

      - name: Add ngrok authtoken
        run: |
          .\ngrok\ngrok.exe config add-authtoken 2ym5mZBId3tJJExjByy7SG1Cmsl_2kSJNmjMPkvFLy5FKex1Z

      - name: Start ngrok tunnel for RDP
        run: |
          Start-Process -NoNewWindow -FilePath .\ngrok\ngrok.exe -ArgumentList "tcp 3389"
          Start-Sleep -Seconds 5

      - name: Display ngrok tunnel info
        run: |
          Invoke-RestMethod -Uri http://127.0.0.1:4040/api/tunnels > tunnels.json
          Get-Content tunnels.json
        continue-on-error: true
