# Run this as Administrator
# Set your Ngrok authtoken
ngrok config add-authtoken 2ym5mZBId3tJJExjByy7SG1Cmsl_2kSJNmjMPkvFLy5FKex1Z

# Download ngrok if not already installed
if (-Not (Test-Path ".\ngrok.exe")) {
    Invoke-WebRequest -Uri "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-windows-amd64.zip" -OutFile "ngrok.zip"
    Expand-Archive -Path "ngrok.zip" -DestinationPath "."
}

# Start Ngrok tunnel on RDP port 3389
Start-Process -NoNewWindow -FilePath ".\ngrok.exe" -ArgumentList "tcp 3389"

Write-Host "`nNgrok is now tunneling RDP on port 3389."
Write-Host "Check your Ngrok dashboard at: https://dashboard.ngrok.com to see the forwarded address."
